In [3]:
import pandas as pd
import numpy as np
ages = [20,22,25,27,29,21,23,31,62,67,45,32]
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (25, 35], ..., (25, 35], (60, 100], (60, 100], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [4]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     4
(60, 100]    2
(35, 60]     1
dtype: int64

In [5]:
pd.cut(ages,[18,26,35,61,100])

[(18, 26], (18, 26], (18, 26], (26, 35], (26, 35], ..., (26, 35], (61, 100], (61, 100], (35, 61], (26, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 26] < (26, 35] < (35, 61] < (61, 100]]

In [6]:
group_names  = ['youth','youngadult','middleaged','senior']

In [9]:
pd.cut(ages,[18,26,35,61,100], labels=group_names)

[youth, youth, youth, youngadult, youngadult, ..., youngadult, senior, senior, middleaged, youngadult]
Length: 12
Categories (4, object): [youth < youngadult < middleaged < senior]

In [12]:
data = np.random.randn(1000)

In [13]:
data

array([-0.48421629,  0.60940628, -1.20458623,  0.8360335 , -0.77487137,
        0.41898072, -0.12635758,  0.78957545,  1.90778023, -0.11032739,
       -0.38319704,  2.07920846,  0.37855653, -1.00118129, -1.03349726,
        0.79527042, -0.21176993, -0.19620849,  0.59795129,  1.3402992 ,
       -0.9653729 , -1.83026769,  0.61650072, -0.89008422,  0.46882258,
        0.19268906,  1.25430638,  0.38421208,  0.97590157,  0.62414893,
        0.77985407,  0.42295134,  0.73560112, -0.0233259 ,  1.0159327 ,
       -1.02851632, -2.62106854,  0.68067086, -0.69205772,  0.42274131,
       -0.54622946, -0.37701185,  0.53683571, -1.85313238, -0.27679164,
        0.27339926, -1.20148338,  0.27808272,  1.54672924, -0.87708058,
       -1.06623092, -0.9315779 , -0.08548356, -0.11127658, -0.52182349,
        0.55120774, -0.0463282 , -0.0095283 ,  0.09641792,  0.80328285,
       -0.70584901,  0.63406554, -1.00640763,  0.10920757, -1.03703633,
        0.6917221 , -1.21414138,  0.08328308,  0.76297499,  0.59

In [16]:
cats = pd.qcut(data,4)

In [17]:
pd.value_counts(cats)

(0.674, 3.685]                   250
(0.0521, 0.674]                  250
(-0.672, 0.0521]                 250
(-3.5109999999999997, -0.672]    250
dtype: int64

In [18]:
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-1.245, 0.0521], (0.0521, 1.296], (-1.245, 0.0521], (0.0521, 1.296], (-1.245, 0.0521], ..., (0.0521, 1.296], (0.0521, 1.296], (0.0521, 1.296], (-1.245, 0.0521], (-1.245, 0.0521]]
Length: 1000
Categories (4, interval[float64]): [(-3.5109999999999997, -1.245] < (-1.245, 0.0521] < (0.0521, 1.296] < (1.296, 3.685]]

In [19]:
data= pd.DataFrame(np.random.randn(1000,4))

In [20]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.045502     0.013404     0.082390    -0.007449
std       0.993663     1.051687     0.997174     0.963294
min      -3.392584    -4.000733    -2.944383    -3.370974
25%      -0.726233    -0.681944    -0.621553    -0.602548
50%      -0.050415     0.034123     0.067424    -0.025248
75%       0.615184     0.727070     0.716879     0.660380
max       3.313291     3.493423     3.493145     2.943340

In [21]:
col = data[2]

In [22]:
col

0      0.074841
1      0.807942
2      1.168949
3     -0.522358
4     -0.241248
         ...   
995    1.546514
996   -1.693947
997   -1.221887
998    0.888261
999    1.367845
Name: 2, Length: 1000, dtype: float64

In [23]:
col[np.abs(col)>3]

14     3.379065
109    3.493145
194    3.274404
Name: 2, dtype: float64

In [24]:
data[np.abs(data)>3] =np.sign(data)*3

In [25]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.045746     0.013997     0.081243    -0.007065
std       0.990383     1.045736     0.993576     0.962025
min      -3.000000    -3.000000    -2.944383    -3.000000
25%      -0.726233    -0.681944    -0.621553    -0.602548
50%      -0.050415     0.034123     0.067424    -0.025248
75%       0.615184     0.727070     0.716879     0.660380
max       3.000000     3.000000     3.000000     2.943340

In [26]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0 -1.0  1.0  1.0
2  1.0  1.0  1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0 -1.0  1.0

In [27]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [28]:
sampler = np.random.permutation(5)

In [29]:
sampler

array([1, 2, 4, 3, 0])

In [30]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
4  16  17  18  19
3  12  13  14  15
0   0   1   2   3

In [31]:
choices = pd.Series([5,7,-1,6,4])

In [32]:
draws = choices.sample(n=10,replace=True)

In [33]:
draws

2   -1
1    7
3    6
2   -1
1    7
3    6
0    5
1    7
4    4
4    4
dtype: int64

In [34]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [35]:
sampler = np.random.permutation(5)

In [36]:
sampler

array([4, 2, 0, 1, 3])

In [37]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})

In [38]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [39]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [40]:
dummies = pd.get_dummies(df['key'],prefix = 'key')

In [41]:
df_with_dummy = df[['data1']].join(dummies)

In [42]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [43]:
val = 'a,b,guido'

In [44]:
val.split(',')

['a', 'b', 'guido']

In [47]:
pieces = [x.strip() for x in val.split(',')]

In [48]:
pieces

['a', 'b', 'guido']

In [49]:
first, second, third = pieces

In [50]:
pieces

['a', 'b', 'guido']

In [53]:
first + '::' + second + '::' + third

'a::b::guido'

In [54]:
'::'.join(pieces)

'a::b::guido'

In [55]:
import re

In [56]:
text = 'foo bar\t baz \t qux'

In [57]:
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [60]:
regex.findall(text)

[' ', '\t ', ' \t ']

In [59]:
regex = re.compile('\s+')